Add API description
Panpipe-team/panpipe-common pull request #17
Opened 2024-11-05 14:54 UTC by schtschee

2024-11-05 22:44 UTC, gri-gri requested changes
1. Где ручка для изменения результата/отметки привычки?
2. Важная фигня про таймстемпы результатов, ещё раз. Это не дата, когда таймстемп был создан/изменён и т.д. Это таймстемпы во времени, разделённые согласно периодичности. Например, два таймстемпа в день или два таймстемпа в месяц. Это довольно конкретные вещи, генерирующиеся на стороне бэка. Так что нужна ручка для запроса доступных таймстемпов или, что, наверное, лучше, в запросе про результаты возвращать словарь, где для таймстемпа указан либо результат - в MVP значение, потом ещё и коммент, либо null, что означает, что таймстемп доступен.

2024-11-05 22:44 UTC, gri-gri commented on docs/api-description.md
> +### POST auth/signIn
Если у вас не сложно, `/login`, пожалуйста

2024-11-05 22:44 UTC, gri-gri commented on docs/api-description.md
> +name : string }
Нет в MVP

2024-11-05 22:44 UTC, gri-gri commented on docs/api-description.md
> +### POST auth/signUp
Если у вас не сложно, `/register`, пожалуйста

2024-11-05 22:44 UTC, gri-gri commented on docs/api-description.md
> +?name : string,\
Нет в MVP

2024-11-05 22:44 UTC, gri-gri commented on docs/api-description.md
> +name : string }
Нет в MVP

2024-11-05 22:44 UTC, gri-gri commented on docs/api-description.md
> +### POST auth/signOut
Если у вас не сложно, `/logout`, пожалуйста

2024-11-05 22:44 UTC, gri-gri commented on docs/api-description.md
> +### GET /users/{user_id} - получить пользователя по id
Зачем? Для MVP, вроде, не нужно

2024-11-05 22:44 UTC, gri-gri commented on docs/api-description.md
> +description : string,\
Нет в MVP

2024-11-05 22:44 UTC, gri-gri commented on docs/api-description.md
> +### GET /habitemplates/{id} - получить шаблон по id
Зачем? Если вся информация и так приходит по общему

2024-11-05 22:44 UTC, gri-gri commented on docs/api-description.md
> +{ template_id: uuid,\
А где тут инфа про параметры привычки? Или типо через темплейт получать?
Это порочная практика, в будущем это так работать не будет

2024-11-05 22:44 UTC, gri-gri commented on docs/api-description.md
> +&emsp;date : dateTime,\
Вот тут хз, как бы так в API обозначить, что это не случайные datetime, а конкретные таймстемпы, на которые разбивается привычка по периодичности. Будет не "23:09:58 25.09.2016", а "0:0:0 25.09.2016". Или, например, для привычки "два раза в день" таймстемпы "10:00:00 25.09.2016" и "20:00:00 25.09.2016" вне зависимости от времени занесения. Со случайными таймстемпами тяжело работать.
Хотя, наверное, в API никак не обозначить, эх...
Если за минуту идей не придёт, как это обозначить - resolve.

2024-11-05 22:44 UTC, gri-gri commented on docs/api-description.md
> +### GET /habits/findByUser - получить все привычки пользователя
У нас почти все запросы аутентифицированы. В контексте запроса всегда будет пользователь. Так что должно быть просто `GET /habits` - он и так вернёт все привычки пользователя. Не хотелось бы выставлять наружу возможность запрашивать привычки других пользователей.

2024-11-05 22:44 UTC, gri-gri commented on docs/api-description.md
> +[{ habit_id : uuid}, ...]  //хотим возвращать всю инфу или только id?
Такие вещи и надо решить, когда проектируешь API. Тут, наверное, всё равно, просто выбери один вариант

2024-11-05 22:44 UTC, gri-gri commented on docs/api-description.md
> +### POST /habits/addResult - добавить результат к привычке
Нейминг не по REST. Должно быть `POST /habits/{id}/results`. 
Эндпоинты - это не RPC, не вызов функции, а операции с ресурсами.
Id ресурса должен быть вынесен в строчку

2024-11-05 22:44 UTC, gri-gri commented on docs/api-description.md
> +### GET /groups/findByUser - получить все группы пользователя
То же, что и про привычки пользователей

2024-11-05 22:44 UTC, gri-gri commented on docs/api-description.md
> +habits : [{ habit_id : uuid }, ...] }
Нет в MVP

2024-11-05 22:44 UTC, gri-gri commented on docs/api-description.md
> +### PUT /groups/addHabit - добавить в группу привычку
То же, что и про привычки: `POST /groups/{id}/habits`.
Но вообще этого нет в MVP

2024-11-05 22:44 UTC, gri-gri commented on docs/api-description.md
> +&emsp;comment: string }, ...]}
Нет в MVP

2024-11-05 22:44 UTC, gri-gri commented on docs/api-description.md
> +&emsp;comment: string } }
Нет в MVP

2024-11-05 22:44 UTC, gri-gri commented on docs/api-description.md
> +&emsp;comment: string }, ...]}
Нет в MVP

2024-11-06 11:48 UTC, schtschee commented on docs/api-description.md
> +name : string }
а на фронте уже есть))

2024-11-06 11:56 UTC, gri-gri commented on docs/api-description.md
> +name : string }
![image](https://github.com/user-attachments/assets/5068b941-4fa3-44bf-bec9-f619262fc274)

2024-11-06 12:05 UTC, gri-gri commented on docs/api-description.md
> +name : string }
Тогда оставляй, тред резолвь. 
Если хочешь, то комментарий у результата привычки тоже можно оставить, на бэке не проблема, сделаем. У фронта, кажется, сложнее

2024-11-06 12:28 UTC, schtschee commented on docs/api-description.md
> +{ template_id: uuid,\
Окей, тогда в привычке дублируем данные из шаблона

2024-11-06 12:29 UTC, schtschee commented on docs/api-description.md
> +### POST /habits/addResult - добавить результат к привычке
ок

2024-11-06 12:29 UTC, schtschee commented on docs/api-description.md
> +[{ habit_id : uuid}, ...]  //хотим возвращать всю инфу или только id?
ок

2024-11-06 12:38 UTC, schtschee commented on docs/api-description.md
> +&emsp;date : dateTime,\
Если я правильно поняла то при создании привычки с ней сразу создается массив "пустых" отметок (тогда им date можно задать при создании). 
Можно сделать api чтобы получать этот массив, потом выбирать из него отметку, которую хотим изменить, и передавать только id отметки и value - POST /habits/{result_id}/results + {value : string}

2024-11-06 12:49 UTC, gri-gri commented on docs/api-description.md
> +### POST auth/signIn
Написал, ждём ответа

2024-11-06 13:14 UTC, gri-gri commented on docs/api-description.md
> +&emsp;date : dateTime,\
При такой реализации предлагаю, чтобы отметка была в следующем формате - указываю список отметок:
`results: [ { id: uuid, result: { value: string } }, { id: uuid, result: null } ]` или как-то так. Потому что может быть несколько параметров у результата: значение, комментарий и прочее. Хотелось бы махом установить это как null.

2024-11-06 13:15 UTC, gri-gri commented on docs/api-description.md
> +&emsp;date : dateTime,\
> Но ручка по добавлению отметки тогда должна называться PUT /habits/{habit-id}/results/{result-id}

Кстати, ручка по изменению отметки точно такая же, удобно!
Получается, п. 1 и 2 из моего первого ревью тоже решены.

2024-11-06 15:01 UTC, schtschee commented on docs/api-description.md
> +habits : [{ habit_id : uuid,\
удалила

2024-11-06 15:53 UTC, gri-gri requested changes

2024-11-06 15:53 UTC, gri-gri commented on docs/api-description.md
> +&emsp;name : string,\
Эта и 3 ниже строки, видимо, не удалила при удалении привычек в группах

2024-11-06 15:53 UTC, gri-gri commented on docs/api-description.md
> +### POST auth/login
Без префикса /auth
Уточняю про это в чатике

2024-11-06 15:55 UTC, gri-gri commented on docs/api-description.md
> +&emsp;value : string }, ...]}
Здесь в результате будет null обязательно

2024-11-06 16:07 UTC, schtschee commented on docs/api-description.md
> +&emsp;date : dateTime,\
> При такой реализации предлагаю, чтобы отметка была в следующем формате - указываю список отметок: `results: [ { id: uuid, result: { value: string } }, { id: uuid, result: null } ]` или как-то так. Потому что может быть несколько параметров у результата: значение, комментарий и прочее. Хотелось бы махом установить это как null.

А таймстемп тогда где? 
{ id: uuid, result: { date : datetime,  value: string } }
или
{ id: uuid, date : datetime, result: { value: string } }
Как будто второй вариант правильнее, если мы таймстемпы сразу при создании рассчитываем. 
Тогда вопрос удобнее ли выделять result: { value: string, comment : string } или занулить сразу value и comment - я хз, мне пофиг на самом деле))

2024-11-06 17:09 UTC, merged