Доработка api
Panpipe-team/panpipe-common pull request #22
Opened 2024-12-04 22:53 UTC by schtschee

попытка раз

2024-12-06 14:12 UTC, gri-gri requested changes
1. Сделай, пожалуйста, по аналогии с функциональными требованиями: два разных файла, для mvp и финальный. Не забудь ссылку в ридмишке. Добавь в начале файла префиксы url, о которых договаривались: `/api/v1` и какой там для финальной.
2. Где ручка для изменения имени пользователя?
3. Давай перенесём ручку выше и ручку для изменения пароля куда-нибудь в `/account`
4. Periodicity надо заменить на то, что договорились в чате
5. Где ручки на создание различных групповых привычек?
6. Не нужна ручка на получение всех групповых привычек с индивидуальным зачётом? Короче, с этими двумя типами надо разобраться

2024-12-06 14:12 UTC, gri-gri commented on docs/api-description.md
> +### POST /habits/template - создать привычку по шаблону
Такой URI обозначает создание шаблона. Предлагаю `POST /templated-habits`

2024-12-06 14:12 UTC, gri-gri commented on docs/api-description.md
>  participants : [{ userId : uuid, ...}]}
Ну тут же не совсем так, на самом деле. Тут `participants: [ { userId: uuid }, ... ]`. Другое дело, что сейчас появились имена, может, их туда надо или логины...

2024-12-06 14:12 UTC, gri-gri commented on docs/api-description.md
> +participants : [{ userId : uuid, ...}]}
То же самое, что в ручке GET

2024-12-06 14:12 UTC, gri-gri commented on docs/api-description.md
> +### PUT /groups/{groupId}/participants - выйти из группы
Предлагаю `DELETE /groups/{groupId}/participants/{userId}`

2024-12-06 14:12 UTC, gri-gri commented on docs/api-description.md
> +### GET /groups/{groupId}/habits - получить групповые привычки
Это групповые привычки с общим зачётом?

2024-12-06 14:12 UTC, gri-gri commented on docs/api-description.md
> +### GET /groups/habits/{habitId} - получить групповую с индивидуальным зачетом привычку по id
Пропущено `{groupId}`

2024-12-07 14:09 UTC, schtschee commented on docs/api-description.md
> +### GET /users - получить всех пользователей
хороший вопрос
значит не нужна

2024-12-07 14:15 UTC, schtschee commented on docs/api-description.md
> +### PUT /groups/{groupId}/participants - выйти из группы
А нам разве надо id пользователя передавать? 
Он же только сам себя удалить может, не?

2024-12-07 16:20 UTC, schtschee commented on docs/api-description.md
>  participants : [{ userId : uuid, ...}]}
Давай будем id и имя возвращать для участников

2024-12-08 07:21 UTC, gri-gri commented on docs/api-description.md
> +### PUT /groups/{groupId}/participants - выйти из группы
Да, но так надо по REST'у. Захочет не себя удалить - бэк вернёт 401 Unauthorized.

2024-12-08 12:52 UTC, gri-gri commented on docs/api-description.md
> +### PUT /groups/{groupId}/participants - выйти из группы
Ладно, пофиг, я там отдельный ПР сделал со всеми предложениями

2024-12-08 13:55 UTC, gri-gri commented
Надо добавить api по статистике

2024-12-08 16:40 UTC, gri-gri approved these changes

2024-12-08 16:40 UTC, merged